### ISSUE TITLE
fontforge.font attributes are strings, not bytes

### ISSUE THREAD

**Issue by GreyAlien502** [keidax/bdf2ttf.py#2]
Fontforge Version: 20201107
Python Version: 3.9.6

Running bdf2ttf on a font gives the following error:
```
bdf2ttf -o build/without-diacritics.ttf build/nec-in.bdf
Traceback (most recent call last):
  File "/home/greyalien502/.local/bin/bdf2ttf", line 8, in <module>
    sys.exit(main())
  File "/home/greyalien502/.local/lib/python3.9/site-packages/bdf2ttf/convert.py", line 141, in main
    convert_bdf(args.infile, outfile=args.out, feature_file=args.feature_file)
  File "/home/greyalien502/.local/lib/python3.9/site-packages/bdf2ttf/convert.py", line 86, in convert_bdf
    map_attributes(bdf, font)
  File "/home/greyalien502/.local/lib/python3.9/site-packages/bdf2ttf/convert.py", line 28, in map_attributes
    setattr(font, attr_map[attr_name], attr_value)
TypeError: bad argument type for built-in operation
```
Does anyone know what change broke it?
My fix is just to convert to strings before setting attributes,
but idk if that would break it with an older version of fontforge.

**Comment by keidax** [comment]
Thanks for the report! This is fixed in https://github.com/keidax/bdf2ttf.py/pull/3

**Comment by GreyAlien502** [comment]
Cool, thanks for the fix!
